# config file for binds

$mainMod = SUPER
$terminal = alacritty
$fileManager = dolphin
$menu = wofi --show drun
$fullmenu = wofi --show run
bindel = , XF86AudioRaiseVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ +5%
bindel = , XF86AudioLowerVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ -5%
bindl =  , XF86AudioMute,        exec, pactl set-sink-mute   @DEFAULT_SINK@ toggle

   # open terminal
bind = $mainMod, Q, exec, $terminal
   # kill active window
bind = $mainMod, C, killactive,
   # shut down hyprland
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
   # open file manager (dolphin)
bind = $mainMod, E, exec, $fileManager
   # fullscreen select window
bind = $mainMod, F, fullscreen, 1
   # floating select window
bind = $mainMod SHIFT, F, togglefloating
   # open menu (wofi) for executable programs
bind = $mainMod, R, exec, $menu
bind = $mainMod SHIFT, R, exec, $fullmenu
   # refresh hyprland
bind = $mainMod, N, exec, hyprctl reload
   # hyprshot screenshot
bind = $mainMod, S, exec, hyprshot -m region

# switching windows
bind = $mainMod, left , movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up   , movefocus, u
bind = $mainMod, down , movefocus, d
# vim binds
bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d
# moving windows
bind = $mainMod SHIFT, left , swapwindow, l
bind = $mainMod SHIFT, right, swapwindow, r
bind = $mainMod SHIFT, up   , swapwindow, u
bind = $mainMod SHIFT, down , swapwindow, d

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# bind = $mainMod, =, cyclenext, none
# bind = $mainMod, -, cyclenext, prev

# workspaces 1-5
bind = $mainMod, code:25, workspace, h
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
# push window to workspace
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
# cycle workspaces
allow_workspace_cycles = true
bind = , mouse_right, workspace, +1
bind = , mouse_left, workspace, e-1
