# hyprland startup commands

# background gif
exec-once = awww-daemon

# toolbar
exec-once = hyprpanel

# screen share tools
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP


exec-once = sleep 5
exec-once = alacritty
