# hyprland animations config

bezier = jump, 0.5,-0.2,0.9,2
bezier = easeIn, 0.1,0.8,0.2,1
bezier = linear, 0,0,1,1
animation = workspacesOut, 1, 5, jump, slidefade
animation = workspacesIn, 1, 7, easeIn, slide
animation = windows, 1, 7, easeIn, slide
animation = borderangle, 1, 30, linear, loop
