# hyprland startup commands

# background
exec-once = awww-daemon &
exec-once = wal -R

# toolbar
exec-once = hyprpanel

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

exec-once = sleep 5 && alacritty
